language: java
jdk:
  - oraclejdk8
  
before_install:
  - sudo apt-get sudo apt-get update -qq
  - sudo apt-get install --only-upgrade -y oracle-java8-installer
  
install:
  - mvn install -DskipTests=true -DskipUnitTests=true

script:
  - mvn test -Dgrinder.display.tree.util.ui=false -Dtrace.level=off -Djustification.level=off
